/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import gestorHotel.*;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author HP
 */
public class TelaReservas extends javax.swing.JFrame {

    /**
     * Creates new form MenuReservas
     */
    Vector vectorR = new Vector();
    Vector vectorQ = new Vector();
    
    public TelaReservas() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconHotel.png")));
        try{
            vectorR = (Vector) FicheiroReservas.ler();
            vectorQ = (Vector) FicheiroQuartos.ler();
        }catch(Exception e){
            e.printStackTrace();
        }
        tabelaIn();
    }
    
    void tabelaIn() {
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        Object[] linha;
        linha = new Object[5];
        Reservas reserva;
        
        double preco;
        for (int i = 0; i < vectorR.size(); i++) {
            reserva = (Reservas) vectorR.get(i);
            linha[0] = reserva.getNome();
            linha[1] = reserva.getTelefone();
            linha[2] = reserva.getEmai();
            linha[3] = reserva.getQuarto();
            preco=reserva.getTempo()*reserva.getPreco();
            linha[4]=preco;
            modelo.addRow(linha);
        }

    }
    
    void recibo(){
        DefaultTableModel m = (DefaultTableModel) tabela.getModel();
        
        Quarto quarto;
        for (int i = 0; i < vectorQ.size(); i++) {
            quarto = (Quarto) vectorQ.get(i);
            if((int)m.getValueAt(tabela.getSelectedRow(), 3) == (quarto.getNrQuarto())){
                quarto.setDisponivel("Disponivel");
                quarto.setClienteNome("");
                quarto.setClienteId(0);
                System.out.println("Done Change to Available");
                try {
                    FicheiroQuartos.guardar(vectorQ);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            }
        }
        
        Reservas reserva;
        for (int i = 0; i < vectorR.size(); i++) {
            reserva = (Reservas) vectorR.get(i);
            if ((int)m.getValueAt(tabela.getSelectedRow(), 3) ==(reserva.getQuarto())) {
                vectorR.remove(i);
                System.out.println("Done remove");
                try {
                    FicheiroReservas.guardar(vectorR);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            }
        }
        
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(new File("RECIBO.TXT")));
            bw.write("Nome: " + m.getValueAt(tabela.getSelectedRow(), 0) + "\n");
            bw.write("Quarto: " + m.getValueAt(tabela.getSelectedRow(), 3) + "\n");
            bw.write("Preco: " + m.getValueAt(tabela.getSelectedRow(), 4) + "\n");
            bw.write("Obrigado por visitar o HOTEL BELO HORIZONTE, esperamos ve-lo novamente!");
            bw.close();
            Desktop d = Desktop.getDesktop();
            d.open(new File("RECIBO.TXT"));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        m.removeRow(tabela.getSelectedRow());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Reservas");
        setResizable(false);

        tabela.setBackground(new java.awt.Color(204, 204, 255));
        tabela.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabela.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone", "E-mail ", "Quarto", "Preco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/IconHotel.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HOTEL BELO HORIZONTE");

        jButton1.setText("Emitir Recibo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        recibo();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
